# Generated by Django 4.2.1 on 2023-05-22 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Org',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('created', models.DateTimeField(verbose_name='date created')),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('maintainers', models.CharField(max_length=200)),
                ('created', models.DateTimeField(verbose_name='date created')),
                ('versions', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('license', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.CharField(max_length=200)),
                ('content', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('created', models.DateTimeField(verbose_name='date created')),
                ('state', models.CharField(max_length=200)),
            ],
        ),
    ]
