# Generated by Django 4.2.1 on 2023-05-22 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend_mvp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='pkg_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='backend_mvp.package'),
        ),
    ]
