# Generated by Django 4.2.1 on 2023-05-24 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_mvp', '0002_version_pkg_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='version',
            old_name='version_number',
            new_name='tag_hash',
        ),
        migrations.AddField(
            model_name='version',
            name='tag_name',
            field=models.CharField(default='default', max_length=200),
            preserve_default=False,
        ),
    ]
