# Generated by Django 4.2.1 on 2023-05-24 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_mvp', '0003_rename_version_number_version_tag_hash_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='version',
            name='state',
        ),
        migrations.AddField(
            model_name='package',
            name='dev_status',
            field=models.CharField(default='alpha', max_length=200),
            preserve_default=False,
        ),
    ]
