# Generated by Django 4.2.1 on 2023-05-24 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_mvp', '0004_remove_version_state_package_dev_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='LabelGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='package',
            name='dev_status',
        ),
        migrations.RemoveField(
            model_name='package',
            name='type',
        ),
    ]
