# Generated by Django 4.2.1 on 2023-05-24 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_mvp', '0005_label_labelgroup_remove_package_dev_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='license',
        ),
    ]
