# Generated by Django 4.2.1 on 2023-05-24 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_mvp', '0006_remove_package_license'),
    ]

    operations = [
        migrations.RenameField(
            model_name='version',
            old_name='pkg_name',
            new_name='package',
        ),
    ]
